using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class Unit : MonoBehaviour
{
    public UnitInfo unitInfo;
    public bool isOrange;
    public bool hasTarget;//如果有目斯,否t朝王移
    public bool isDead;
    public int currentHp;

    //M件引用
    public Animator animator;
    public NavMeshAgent meshAgent;

    //其他的引用
    public Unit defaultTarget; //默J攻裟:王
    public Unit targetUnit;//目斯挝
    public List<Unit> targetsList = new List<Unit>();//前攻艄可x橙说牧斜(主臃)
    public List<Unit> attackerList = new List<Unit>(); //攻粑的橙肆斜(被臃)


    // Start is called before the first frame update
    protected virtual void Start()
    {
        animator = GetComponentInChildren<Animator>();
        meshAgent = GetComponent<NavMeshAgent>();
        GetComponentInChildren<SphereCollider>().radius = unitInfo.attackArea * 2;
    }


    /// <summary>
    /// 挝灰
    /// </summary>
    protected virtual void UnitMove()
    {
        //有目
        if (hasTarget)
        {
            //目]有N,]有死亡
            if (targetUnit != null && !targetUnit.isDead)
            {
                //朝目艘
                meshAgent.SetDestination(targetUnit.transform.position);
                JudegeIfReachTargetPos(transform.position, targetUnit.transform.position);
            }
            else
            {
                //重置目
                Resettarget();
            }
        }
        //]有目
        else
        {
            //@取前默J目宋恢
            GameController.Instance.UnitGetTargetPos(this, isOrange);
            //默J目耸欠榭
            if (defaultTarget != null)
            {

                //朝默J目艘
                meshAgent.SetDestination(defaultTarget.transform.position);
                JudegeIfReachTargetPos(transform.position, defaultTarget.transform.position);
            }
        }
    }

    /// <summary>
    /// 判嗍欠襁_到攻艄KM行移
    /// </summary>
    /// <param name="currentPos"></param>
    /// <param name="target"></param>
    public void JudegeIfReachTargetPos(Vector3 currentPos, Vector3 target)
    {
        //]有到_攻艄
        if (Vector3.Distance(currentPos, target) >= unitInfo.attackArea)
        {
            //绦邢嚓P行
            UnitBehaviour();
        }
        //到_攻艄
        else
        {
            meshAgent.isStopped = true;
            //赢控制器播放攻赢
            animator.SetBool("isAttacking", true);
            animator.SetBool("isMoving", false);
        }
    }

    private void Resettarget()
    {

    }

    /// <summary>
    /// 挝绦行 
    /// </summary>
    protected virtual void UnitBehaviour()
    {
        //赢控制器播放移赢
        animator.SetBool("isAttacking", false);
        animator.SetBool("isMoving", true);

    }

    /// <summary>
    /// 受到害
    /// </summary>
    /// <param name="damageValue">攻抵</param>
    /// <param name="attacker">攻粽(攻粑的人)</param>
    private void TakeDamage(int damageValue, Unit attacker)
    {

    }

    /// <summary>
    /// 死亡
    /// </summary>
    /// <param name="attacker">攻粽(攻粑的人)</param>
    protected virtual void Dead(Unit attacker)
    {

    }
    /// <summary>
    /// 攻赢事件
    /// </summary>
    public virtual void AttackAnimationEvent() 
    {
        if (hasTarget)
        {
            transform.LookAt(targetUnit.transform);
        }
        else 
        {
            transform.LookAt(defaultTarget.transform);
        }
        //橙丝垩
        if (targetUnit)
        {
            targetUnit.TakeDamage(unitInfo.attackValue, this);
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Tag")) 
        {
            Unit unit = other.GetComponentInParent<Unit>();
            if (isOrange != unit.isOrange) 
            {
                targetsList.Add(unit);
                unit.AddAttackerToList(this);
            }
        }
        
    }
    /// <summary>
    /// 我被其他想要攻粑的Lzy, 所以需要把攻粑的ο筇砑拥焦粽吡斜碇 (攻粽呤侵臃,  我是被臃)
    /// </summary>
    /// <param name="unit"></param>
    public void AddAttackerToList(Unit unit) 
    {
        attackerList.Add(unit);
    }
}
/// <summary>
/// Unit Information
/// </summary>
//[Serializable]
public struct UnitInfo 
{
    public int id;
    public string unitName;
    public int cost;
    public int hp;
    public float attackArea;
    public float speed;
    public int attackValue;
    public bool canCreateAnywhere;
}

